name: Build and Run NGINX Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name: [my-nginx, my-custom-nginx]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ matrix.image-name }} .
    
    - name: Run Docker container
      run: |
        docker run -d -p 80:80 --name my-nginx-container ${{ matrix.image-name }}
